server:
  port: 8082

spring:
  application:
    name: Activity-Service

  data:
    mongodb:
      uri: mongodb://localhost:27017/aiactivity_fitness
      database: aiactivity_fitness

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: o org.springframework.kafka.support.serializer.JsonDeserializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

kafka:
  topic:
    name: activity-events
