server:
  port: 8082

spring:
  application:
    name: Activity-Service
  data:
    mongodb:
      uri: mongodb://localhost:27017/aiacitivity_fitness
      database: aiacitivity_fitness

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.web.reactive.function.client: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG

