spring:
  application:
    name: ai-gemini-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/ai-recomendation
      database: ai-recomendation

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8083
