spring:
  application:
    name: ai-gemini-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/ai-recomendation
      database: ai-recomendation

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: activity-processor-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type:  com.fitness.ai_gemini_service.modal.Activity # <-- replace with your DTO class
        spring.json.trusted.packages: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

kafka:
  topic:
    name: activity-events

server:
  port: 8083
